services:
  openresty1:
    # image: openresty/openresty:1.25.3.1-1-jammy
    build:
      context: .
      dockerfile: Dockerfile
    image: openresty:1.25.3.1-1
    container_name: 'openresty1'
    restart: 'always'
    ports:
      - '80:80'
      - '443:443'
    environment:
      SERVER: "openresty1"
    volumes:
      - './openresty1/log:/var/log/openresty'
      - './openresty1/conf.d:/etc/nginx/conf.d'
      - './nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './data:/data'
      - './openresty1/cert:/usr/local/openresty/nginx/cert'
    networks:
      - lab

  openresty2:
    image: openresty:1.25.3.1-1
    container_name: 'openresty2'
    restart: 'always'
    ports:
      - '8080:8080'
    environment:
      SERVER: "openresty2"
    volumes:
      - './openresty2/log:/var/log/openresty'
      - './openresty2/conf.d:/etc/nginx/conf.d'
      - './nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './data:/data'
      - './openresty2/cert:/usr/local/openresty/nginx/cert'
    networks:
      - lab
    depends_on:
      - openresty1

networks:
  lab:
