services:
  openresty1:
    # image: openresty/openresty:1.25.3.1-1-jammy
    build:
      context: ./build
      dockerfile: ./Dockerfile
    image: openresty:1.25.3.1-1
    container_name: 'openresty1'
    restart: 'always'
    ports:
      - '80:80'
      - '443:443'
      - '5066:5066'
    environment:
      SERVER: "openresty1"
    volumes:
      - './openresty1/log:/var/log/nginx'
      - './openresty1/conf.d:/etc/nginx/conf.d'
      - './nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './data:/data'
      - './openresty1/cert:/usr/local/openresty/nginx/cert'
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  openresty2:
    image: openresty:1.25.3.1-1
    container_name: 'openresty2'
    restart: 'always'
    ports:
      - '8080:8080'
    environment:
      SERVER: "openresty2"
    volumes:
      - './openresty2/log:/var/log/nginx'
      - './openresty2/conf.d:/etc/nginx/conf.d'
      - './nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './data:/data'
      - './openresty2/cert:/usr/local/openresty/nginx/cert'
    networks:
      - lab
    depends_on:
      - openresty1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  goapi:
    build:
        context: ./goapi
    container_name: goapi
    working_dir: /app
    volumes:
      - ./goapi:/app
    ports:
      - "5000:5000"
    command: air
    networks:
      - lab

networks:
  lab:
